[functions.telegram-bot]
enabled = true
verify_jwt = true
import_map = "./functions/telegram-bot/deno.json"
entrypoint = "./functions/telegram-bot/index.ts"

[functions.check-trades]
verify_jwt = false
